default: testacc

LDAP_NONTLS_URL ?= ldap://localhost:1389
LDAP_TLS_URL ?= ldaps://localhost:1636
LDAP_BIND_DN ?= cn=admin,dc=example,dc=com
LDAP_BIND_PASSWORD ?= admin
OPENTOFU ?= tofu
TF_ACC_ENV = TF_ACC=1 TF_ACC_TERRAFORM_PATH=$(OPENTOFU) TF_ACC_PROVIDER_NAMESPACE=lucidsoftware TF_ACC_PROVIDER_HOST=registry.opentofu.org

# Run acceptance tests
.PHONY: testacc
testacc:
	$(TF_ACC_ENV) LDAP_URL=$(LDAP_NONTLS_URL) LDAP_BIND_DN=$(LDAP_BIND_DN) LDAP_BIND_PASSWORD=$(LDAP_BIND_PASSWORD) go test ./... -v $(TESTARGS) -timeout 120m
	$(TF_ACC_ENV) LDAP_URL=$(LDAP_TLS_URL) LDAP_BIND_DN=$(LDAP_BIND_DN) LDAP_BIND_PASSWORD=$(LDAP_BIND_PASSWORD) LDAP_TLS_INSECURE_VERIFY=true go test ./... -v $(TESTARGS) -timeout 120m
	$(TF_ACC_ENV) LDAP_URL=$(LDAP_NONTLS_URL) LDAP_BIND_DN=$(LDAP_BIND_DN) LDAP_BIND_PASSWORD=$(LDAP_BIND_PASSWORD) LDAP_TLS_INSECURE_VERIFY=true LDAP_TLS_USE_STARTTLS=true go test ./... -v $(TESTARGS) -timeout 120m
