# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: latest

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  # Run acceptance tests in a matrix with Terraform and OpenTofu CLI versions
  test:
    name: Acceptance Tests (${{ matrix.tool }} ${{ matrix.version }})
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      LDAP_URL: ldap://localhost:1389
      LDAP_BIND_DN: cn=admin,dc=example,dc=com
      LDAP_BIND_PASSWORD: admin
    strategy:
      fail-fast: false
      matrix:
        include:
          # Terraform
          - tool: terraform
            version: '1.6.*'
          - tool: terraform
            version: '1.9.*'
          # OpenTofu
          - tool: opentofu
            version: '1.7.*'
          - tool: opentofu
            version: '1.8.*'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./contrib/test-ldap-server/docker-compose.yaml"
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Setup Terraform
        if: matrix.tool == 'terraform'
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269ef032 # v3.1.2
        with:
          terraform_version: ${{ matrix.version }}
          terraform_wrapper: false
      - name: Setup OpenTofu
        if: matrix.tool == 'opentofu'
        uses: opentofu/setup-opentofu@592200bd325d4f30b5a4f8fe096a853fe78a8e6a # v1.0.5
        with:
          tofu_version: ${{ matrix.version }}
          tofu_wrapper: false
      - run: go mod download
      - env:
          TF_ACC: "1"
        run: go test -v -cover ./internal/provider/
        timeout-minutes: 10
