# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running testing matrix
  verify:
    name: Build, Test, and Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: go test ./... -coverpkg=./... -coverprofile=coverage.out
      - run: go tool cover -func=coverage.out
      - run: go vet ./...
      - run: staticcheck ./...
      - run: gosec ./...
      - run: govulncheck ./...

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  # Run acceptance tests in a matrix with Terraform CLI versions
  acceptance:
    name: Terraform Provider Acceptance Tests
    needs: verify
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      LDAP_URL: ldaps://localhost:1636
      LDAP_BIND_DN: cn=admin,dc=example,dc=com
      LDAP_BIND_PASSWORD: admin
      LDAP_TLS_INSECURE_VERIFY: "true"
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.13.*'
          - '1.14.*'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: docker compose -f ./contrib/test-ldap-server/docker-compose.yaml up -d
      - run: go mod download
      - env:
          TF_ACC: "1"
        run: go test -v -cover ./internal/provider/
        timeout-minutes: 10
      - if: always()
        run: docker compose -f ./contrib/test-ldap-server/docker-compose.yaml down -v
